RADIOSONDE OBSERVATION   Date: 20/02/2011  Time: 13:28 GMT   Ref No. : 037_001
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       : 1023.0 mb             
HEIGHT         :  250.9 Meter          
TEMPERATURE    :   33.0 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :  100.0 %              SONDE No.  : S15818
WIND DIR.      :  349.0 Deg
WIND VEL.      :   10.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
1023.0    00:00:00    251      33.0  100     33.0   349    10   Ground
1006.3    00:01:48    418       0.7   99      0.6   177    30     Temp
1013.2    00:01:59    361       0.8   99      0.7   182    30       RH
1032.2    00:02:29    205       1.1   85     -1.1   194    30       RH
1038.7    00:02:39    153       1.2   87     -0.7   198    31     Temp
1014.2    00:03:34    441      -0.3   99     -0.4   195    26       RH
 955.1    00:04:03   1134      -0.7   99     -0.9   205    21     Temp
 890.1    00:04:37   1470       1.8   99      1.7   216    27     Temp
 805.3    00:08:00   2190      -0.2   99     -0.4   230    17     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
1023.0    00:00:00    251      33.0  100     33.0   349    10   Ground
1007.4    00:00:30    391      24.0   92     22.6   140    20     Wind
1047.7    00:02:53     81       0.9   90     -0.6   202    32     Wind
 805.3    00:08:00   2190      -0.2   99     -0.4   230    17     Last


--------------
HAINES INDEX
LOW  - 2
MED  - 0
HIGH - 0
