RADIOSONDE OBSERVATION   Date: 21/02/2012  Time: 12:36 GMT   Ref No. : 063_001
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  973.6 mb             
HEIGHT         :  244.9 Meter          
TEMPERATURE    :    0.9 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :  100.0 %              SONDE No.  : S9665
WIND DIR.      :  170.0 Deg
WIND VEL.      :    7.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 973.6    00:00:00    245       0.9  100      0.9   170     7   Ground
 781.8    00:09:29   1989      -5.2   99     -5.3   267    34     Temp
 631.7    00:18:23   3634     -14.7   99    -14.8   221    32     Temp
 580.9    00:21:28   4263     -19.5   97    -19.9   207    30     Temp
 566.4    00:22:14   4450     -21.1   98    -21.3   211    29       RH
 555.1    00:22:58   4599     -23.4   88    -24.9   210    28     Temp
 551.3    00:23:12   4649     -22.8   81    -25.1   209    28       RH
 543.1    00:23:42   4758     -22.9   82    -25.2   211    28     Temp
 459.9    00:29:45   5954     -32.2   65    -36.5   214    32     Temp
 429.0    00:32:04   6442     -36.2   56    -41.8   198    31       RH
 338.3    00:39:12   8043     -49.0   47    -55.3   178    34     Temp
 256.4    00:46:42   9860     -50.9   31    -60.2   245    45     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 973.6    00:00:00    245       0.9  100      0.9   170     7   Ground
 879.9    00:04:34   1054      -1.2   99     -1.3   220    39     Wind
 779.5    00:09:36   2013      -5.5   99     -5.6   267    33     Wind
 600.9    00:20:18   4011     -17.7   97    -18.1   207    28     Wind
 499.8    00:26:36   5362     -27.4   71    -31.0   231    26     Wind
 438.6    00:31:21   6287     -35.0   58    -40.3   206    37     Wind
 371.4    00:36:28   7424     -44.7   52    -50.5   210    24     Wind
 351.5    00:38:11   7790     -47.4   49    -53.4   191    21     Wind
 332.7    00:39:35   8152     -49.2   46    -55.6   184    37     Wind
 288.8    00:43:21   9082     -50.1   37    -58.2   271    30     Wind
 270.5    00:45:21   9510     -49.7   34    -58.5   240    35     Wind
 256.4    00:46:42   9860     -50.9   31    -60.2   245    45     Last


--------------
HAINES INDEX
LOW  - 2
MED  - 3
HIGH - 3
