RADIOSONDE OBSERVATION   Date: 23/01/2012  Time: 06:57 GMT   Ref No. : 058_001
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  968.4 mb             
HEIGHT         :  244.9 Meter          
TEMPERATURE    :    6.5 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :  100.0 %              SONDE No.  : S12630
WIND DIR.      :  170.0 Deg
WIND VEL.      :    8.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 968.4    00:00:00    245       6.5  100      6.5   170     8   Ground
 731.0    00:16:42   2555       6.3   99      6.2   204    47     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 968.4    00:00:00    245       6.5  100      6.5   170     8   Ground
 969.3    00:00:33    237       6.3   99      6.2   270     0     Wind
 962.9    00:00:54    292       6.3   99      6.2   172    13     Wind
 928.6    00:02:31    590       6.3   99      6.2   211    44     Wind
 900.5    00:04:13    842       6.3   99      6.2   231    41     Wind
 731.0    00:16:42   2555       6.3   99      6.2   204    47     Last


--------------
HAINES INDEX
LOW  - 2
MED  - 0
HIGH - 0
