<?php
$time = date("H");
$today = date("w");

$myFile = "/var/www/html/internal/testFile.txt";
$fh = fopen($myFile, 'r');
$theData = fread($fh,filesize($myFile));
fclose($fh);
$fcst = explode("\n", $theData);
$fcst_per1_day = explode(":", $fcst[0]);
$fcst_per1_high = explode(":", $fcst[1]);
$fcst_per1_low = explode(":", $fcst[2]);
$fcst_per1_wd = explode(":", $fcst[3]);
$fcst_per1_ws = explode(":", $fcst[4]);
$fcst_per1_cloud = explode(":", $fcst[5]);
$fcst_per1_precip = explode(":", $fcst[6]);
$fcst_per1_pop = explode(":", $fcst[7]);
$fcst_per2_day = explode(":", $fcst[9]);
$fcst_per2_high = explode(":", $fcst[10]);
$fcst_per2_low = explode(":", $fcst[11]);
$fcst_per2_wd = explode(":", $fcst[12]);
$fcst_per2_ws = explode(":", $fcst[13]);
$fcst_per2_cloud = explode(":", $fcst[14]);
$fcst_per2_precip = explode(":", $fcst[15]);
$fcst_per2_pop = explode(":", $fcst[16]);
$fcst_per3_day = explode(":", $fcst[18]);
$fcst_per3_high = explode(":", $fcst[19]);
$fcst_per3_low = explode(":", $fcst[20]);
$fcst_per3_wd = explode(":", $fcst[21]);
$fcst_per3_ws = explode(":", $fcst[22]);
$fcst_per3_cloud = explode(":", $fcst[23]);
$fcst_per3_precip = explode(":", $fcst[24]);
$fcst_per3_pop = explode(":", $fcst[25]);
$fcst_per4_day = explode(":", $fcst[27]);
$fcst_per4_high = explode(":", $fcst[28]);
$fcst_per4_low = explode(":", $fcst[29]);
$fcst_per4_wd = explode(":", $fcst[30]);
$fcst_per4_ws = explode(":", $fcst[31]);
$fcst_per4_cloud = explode(":", $fcst[32]);
$fcst_per4_precip = explode(":", $fcst[33]);
$fcst_per4_pop = explode(":", $fcst[34]);
$fcst_per5_day = explode(":", $fcst[36]);
$fcst_per5_high = explode(":", $fcst[37]);
$fcst_per5_low = explode(":", $fcst[38]);
$fcst_per5_wd = explode(":", $fcst[39]);
$fcst_per5_ws = explode(":", $fcst[40]);
$fcst_per5_cloud = explode(":", $fcst[41]);
$fcst_per5_precip = explode(":", $fcst[42]);
$fcst_per5_pop = explode(":", $fcst[43]);
$time1 = explode(":", $fcst[44]);
$time2 = $fcst[45];

$myFile2 = "/var/www/html/internal/discussion.txt";
$fh2 = fopen($myFile2, 'r');
$theData2 = fread($fh2,filesize($myFile2));
fclose($fh2);
#$discussion = $theData2;
$discussion = explode("\n", $theData2);
?>
