RADIOSONDE OBSERVATION   Date: 23/01/2012  Time: 07:49 GMT   Ref No. : 059_001
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  967.5 mb             
HEIGHT         :  244.9 Meter          
TEMPERATURE    :    7.6 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :  100.0 %              SONDE No.  : S9615
WIND DIR.      :  160.0 Deg
WIND VEL.      :   13.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 967.5    00:00:00    245       7.6  100      7.6   160    13   Ground
 937.3    00:02:34    507       8.7   99      8.6   199    38     Temp
 894.0    00:04:45    897       4.9   98      4.6   202    41     Temp
 882.5    00:05:27   1002       5.8   99      5.6   200    41     Temp
 853.5    00:06:56   1275       4.0   99      3.8   211    37     Temp
 845.1    00:07:29   1356      -5.8   99     -6.0   215    36     Temp
 841.9    00:07:37   1384      -4.4   98     -4.6   216    36     Temp
 828.0    00:08:18   1516     -16.0   98    -16.2   221    38     Temp
 824.3    00:08:31   1550     -14.2   99    -14.3   224    39     Temp
 821.4    00:08:41   1576     -16.9   99    -17.0   224    39     Temp
 818.8    00:08:52   1600     -15.0   99    -15.1   227    38     Temp
 815.4    00:09:05   1632     -17.8   99    -17.9   227    39     Temp
 812.7    00:09:12   1656     -16.9   99    -17.0   226    39     Temp
 805.1    00:09:36   1726     -19.4   99    -19.6   223    42     Temp
 795.8    00:10:09   1813     -10.9   99    -11.0   224    43     Temp
 794.8    00:10:14   1823     -11.6   99    -11.7   224    43     Temp
 790.9    00:10:38   1861      -4.5   99     -4.7   225    43     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 967.5    00:00:00    245       7.6  100      7.6   160    13   Ground
 966.3    00:00:03    255       7.7   99      7.5   185    18     Wind
 937.3    00:02:34    507       8.7   99      8.6   199    38     Wind
 790.9    00:10:38   1861      -4.5   99     -4.7   225    43     Last


--------------
HAINES INDEX
LOW  - 3
MED  - 0
HIGH - 0
