RADIOSONDE OBSERVATION   Date: 21/05/2016  Time: 18:45 GMT   Ref No. : 175_001
LOCATION: OCT - 0 38.484N 101.386W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  926.6 mb             
HEIGHT         :  213.9 Meter          
TEMPERATURE    :   29.1 Deg            SONDE TYPE : IMET1 AB
HUMIDITY       :   43.0 %              SONDE No.  : 10170
WIND DIR.      :  170.0 Deg
WIND VEL.      :   20.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 926.6    00:00:00    214      29.1   43     15.2   170    20   Ground
 893.3    00:00:51   1332      24.0   44     11.0   179    28     Temp
 878.6    00:01:37   1480      22.6   51     12.0   180    23     Temp
 835.5    00:06:29   1913      18.5   60     10.5   184    29       RH
 825.1    00:07:29   2022      18.1   55      8.9   195    30     Temp
 776.8    00:10:09   2533      13.7   57      5.3   209    30     Temp
 745.8    00:12:57   2875      13.2   25     -6.6   224    23       RH
 744.6    00:13:04   2890      13.2   25     -6.6   224    23     Temp
 673.9    00:18:19   3712       5.5   32    -10.0   226    26     Temp
 610.3    00:24:41   4510      -2.1   47    -11.9   225    26       RH
 583.4    00:27:38   4856      -5.2   36    -17.7   235    24     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 926.6    00:00:00    214      29.1   43     15.2   170    20   Ground
 861.6    00:03:08   1648      21.1   51     10.4   187    23     Wind
 838.0    00:06:07   1889      18.8   59     10.5   175    31     Wind
 828.3    00:07:11   1988      18.2   56      9.2   197    28     Wind
 818.6    00:07:54   2089      17.4   56      8.5   191    32     Wind
 748.0    00:12:46   2851      13.2   26     -6.0   224    22     Wind
 583.4    00:27:38   4856      -5.2   36    -17.7   235    24     Last


--------------
HAINES INDEX
LOW  - 6
MED  - 5
HIGH - 0
