RADIOSONDE OBSERVATION   Date: 27/03/2012  Time: 20:48 GMT   Ref No. : 070_002
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  983.3 mb             
HEIGHT         :  244.9 Meter          
TEMPERATURE    :   19.0 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :   42.6 %              SONDE No.  : S15844
WIND DIR.      :  160.0 Deg
WIND VEL.      :   17.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 983.3    00:00:00    245      19.0   43      6.0   160    17   Ground
 947.0    00:00:47    565      14.6   39      0.9   180    24     Temp
 941.0    00:00:55    619      14.1   40      0.7   180    25       RH
 908.4    00:01:44    915      12.1   49      1.7   197    36     Temp
 895.7    00:02:01   1032      12.4   55      3.7   209    40     Temp
 881.5    00:02:21   1167      15.1   59      7.1   221    42     Temp
 870.0    00:02:39   1278      14.2   72      9.3   227    40       RH
 820.5    00:04:04   1771      10.9   76      6.9   242    44     Temp
 818.6    00:04:08   1790      10.8   77      6.9   243    45       RH
 782.4    00:05:18   2167      10.8   32     -5.3   244    47     Temp
 717.7    00:07:27   2880       5.8   31    -10.2   242    51     Temp
 615.1    00:10:47   4119      -3.9   28    -19.8   251    48       RH
 500.9    00:14:54   5701     -16.8   83    -18.9   274    47     Temp
 486.1    00:15:29   5927     -17.5   88    -19.1   272    42       RH
 426.4    00:18:02   6896     -23.9   85    -25.7   273    41     Temp
 313.0    00:24:00   9069     -42.5   67    -46.1   271    47     Temp
 210.3    00:32:34  11639     -62.8   39    -69.5   262    51     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 983.3    00:00:00    245      19.0   43      6.0   160    17   Ground
 980.1    00:00:03    273      18.1   36      2.9   188    18     Wind
 938.9    00:00:59    637      13.9   41      0.8   181    26     Wind
 798.1    00:04:44   2002      11.2   54      2.2   247    46     Wind
 651.1    00:09:36   3668      -0.6   30    -16.0   243    49     Wind
 495.8    00:15:06   5778     -17.2   85    -19.1   277    45     Wind
 210.3    00:32:34  11639     -62.8   39    -69.5   262    51     Last


--------------
HAINES INDEX
LOW  - 4
MED  - 5
HIGH - 5
