RADIOSONDE OBSERVATION   Date: 14/01/2014  Time: 19:46 GMT   Ref No. : 097_001
LOCATION: OCT - 3 41.464N 87.039W

  Surface Observations                 Sonde Details
------------------------             ------------------------
PRESSURE       :  973.1 mb             
HEIGHT         :  244.9 Meter          
TEMPERATURE    :    0.0 Deg            SONDE TYPE : IMET1 AA
HUMIDITY       :   85.0 %              SONDE No.  : P16158
WIND DIR.      :  210.0 Deg
WIND VEL.      :   12.0 Knot
CLOUD CODE     :  /////
STATION No.    :  99999
STATION NAME   :   KVUM


          SIGNIFICANT LEVELS FOR TEMPERATURE & HUMIDITY

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 973.1    00:00:00    245       0.0   85     -2.2   210    12   Ground
 961.2    00:00:44    344      -0.3   98     -0.5   232    18       RH
 860.5    00:07:32   1221      -5.4   96     -5.9   266    34     Temp
 833.9    00:09:17   1468      -4.3   98     -4.6   245    32       RH
 832.6    00:09:22   1480      -4.3   97     -4.7   245    32     Temp
 758.3    00:15:10   2210      -9.1   80    -11.8   249    40       RH
 758.0    00:15:12   2213      -9.1   80    -11.9   249    40     Temp
 729.4    00:17:33   2509     -12.5   41    -22.9   248    38     Temp
 728.8    00:17:36   2515     -12.4   41    -23.0   248    38       RH
 707.0    00:19:12   2748     -11.8   74    -15.6   242    44     Temp
 698.0    00:19:49   2846     -12.4   70    -16.7   243    45       RH
 688.7    00:20:29   2948     -14.3   33    -26.9   241    45     Temp
 651.8    00:23:14   3365     -14.6   74    -18.2   232    51     Last

          SIGNIFICANT LEVELS FOR WIND

  PRES.     TIME     HGT/MSL  TEMP.   RH     DEWP   W.D    W.S    CODE 
   mb     HH:MM:SS   Meter     °C      %      °C    Deg.   Knots        
-----------------------------------------------------------------------
 973.1    00:00:00    245       0.0   85     -2.2   210    12   Ground
 924.6    00:02:54    654      -1.9   98     -2.1   258    29     Wind
 885.0    00:05:48   1000      -4.0   97     -4.4   264    35     Wind
 861.1    00:07:30   1216      -5.4   96     -5.9   266    34     Wind
 835.8    00:09:10   1450      -4.6   96     -5.1   245    32     Wind
 734.5    00:17:09   2456     -12.0   46    -21.1   251    38     Wind
 651.8    00:23:14   3365     -14.6   74    -18.2   232    51     Last


--------------
HAINES INDEX
LOW  - 1
MED  - 3
HIGH - 0
